source:
  type: "dbt"
  config:
    # Coordinates
    # To use this as-is, set the environment variable DBT_PROJECT_ROOT to the root folder of your dbt project
    manifest_path: "./target/manifest.json"
    catalog_path: "./target/catalog.json"
    sources_path: "./target/sources.json" # optional for freshness
    test_results_path: "./target/run_results.json" # optional for recording dbt test results after running dbt test

    # Options
    target_platform: "databricks" # e.g. bigquery/postgres/etc.

# sink configs
