---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prerequisites
  namespace: monitoring
spec:
  chart:
    spec:
      chart: ./helm/datahub/charts/prerequisites
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system

  interval: 2m

  install:
    remediation:
      retries: -1
    createNamespace: true



  uninstall:
    timeout: 15m



  upgrade:
    remediation:
      retries: -1
      strategy: rollback


  values:

    elasticsearch:
      resources:
        requests:
          cpu: "100m"
          memory: "512M"
        limits:
          cpu: "1000m"
          memory: "512M"


    neo4j:
      enabled: false  # set this to true, if you have a license for the enterprise edition
      acceptLicenseAgreement: "yes"
      defaultDatabase: "graph.db"
      neo4jPassword: "datahub"
      # For better security, add password to neo4j-secrets k8s secret and uncomment below
      # existingPasswordSecret: neo4j-secrets
      core:
        standalone: true

    # Deploys neo4j community version. Only supports single node
    neo4j-community:
      enabled: false   # set this to false, if you have a license for the enterprise edition
      acceptLicenseAgreement: "yes"
      defaultDatabase: "graph.db"
      # For better security, add password to neo4j-secrets k8s secret and uncomment below
      existingPasswordSecret: neo4j-secrets


#    mysql:
#      primary:
#        service:
#          type: LoadBalancer


#    elasticsearch:
#      service:
#        type: LoadBalancer
