---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prerequisites
  namespace: monitoring
spec:
  chart:
    spec:
      chart: ./helm/datahub/charts/prerequisites
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system

  interval: 2m

  install:
    remediation:
      retries: -1
  uninstall:
    timeout: 15m

  upgrade:
    remediation:
      retries: 10

  values:

    elasticsearch:
      resources:
        requests:
          cpu: "100m"
          memory: "512M"
        limits:
          cpu: "1000m"
          memory: "512M"


#    mysql:
#      primary:
#        service:
#          type: LoadBalancer


#    elasticsearch:
#      service:
#        type: LoadBalancer
